/**
 * Country codes for phone registration.
 * Venezuela (+58) first - app oriented to Venezuelans.
 * Flag emoji from ISO 3166-1 alpha-2.
 */
function flagFromIso(iso: string): string {
  return iso
    .toUpperCase()
    .split('')
    .map(c => String.fromCodePoint(0x1f1e6 - 65 + c.charCodeAt(0)))
    .join('');
}

export interface CountryCode {
  iso: string;
  dialCode: string;
  name: string;
  flag: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  {iso: 'VE', dialCode: '+58', name: 'Venezuela', flag: flagFromIso('VE')},
  {iso: 'US', dialCode: '+1', name: 'Estados Unidos', flag: flagFromIso('US')},
  {iso: 'CO', dialCode: '+57', name: 'Colombia', flag: flagFromIso('CO')},
  {iso: 'ES', dialCode: '+34', name: 'España', flag: flagFromIso('ES')},
  {iso: 'MX', dialCode: '+52', name: 'México', flag: flagFromIso('MX')},
  {iso: 'AR', dialCode: '+54', name: 'Argentina', flag: flagFromIso('AR')},
  {iso: 'PE', dialCode: '+51', name: 'Perú', flag: flagFromIso('PE')},
  {iso: 'EC', dialCode: '+593', name: 'Ecuador', flag: flagFromIso('EC')},
  {iso: 'CL', dialCode: '+56', name: 'Chile', flag: flagFromIso('CL')},
  {iso: 'BR', dialCode: '+55', name: 'Brasil', flag: flagFromIso('BR')},
  {iso: 'IT', dialCode: '+39', name: 'Italia', flag: flagFromIso('IT')},
  {iso: 'FR', dialCode: '+33', name: 'Francia', flag: flagFromIso('FR')},
  {iso: 'DE', dialCode: '+49', name: 'Alemania', flag: flagFromIso('DE')},
  {iso: 'GB', dialCode: '+44', name: 'Reino Unido', flag: flagFromIso('GB')},
  {iso: 'CA', dialCode: '+1', name: 'Canadá', flag: flagFromIso('CA')},
  {iso: 'PA', dialCode: '+507', name: 'Panamá', flag: flagFromIso('PA')},
  {iso: 'DO', dialCode: '+1', name: 'Rep. Dominicana', flag: flagFromIso('DO')},
  {iso: 'PR', dialCode: '+1', name: 'Puerto Rico', flag: flagFromIso('PR')},
  {iso: 'UY', dialCode: '+598', name: 'Uruguay', flag: flagFromIso('UY')},
  {iso: 'BO', dialCode: '+591', name: 'Bolivia', flag: flagFromIso('BO')},
  {iso: 'PY', dialCode: '+595', name: 'Paraguay', flag: flagFromIso('PY')},
  {iso: 'CR', dialCode: '+506', name: 'Costa Rica', flag: flagFromIso('CR')},
  {iso: 'GT', dialCode: '+502', name: 'Guatemala', flag: flagFromIso('GT')},
  {iso: 'HN', dialCode: '+504', name: 'Honduras', flag: flagFromIso('HN')},
  {iso: 'SV', dialCode: '+503', name: 'El Salvador', flag: flagFromIso('SV')},
  {iso: 'NI', dialCode: '+505', name: 'Nicaragua', flag: flagFromIso('NI')},
  {iso: 'PT', dialCode: '+351', name: 'Portugal', flag: flagFromIso('PT')},
  {iso: 'NL', dialCode: '+31', name: 'Países Bajos', flag: flagFromIso('NL')},
  {iso: 'RU', dialCode: '+7', name: 'Rusia', flag: flagFromIso('RU')},
  {iso: 'CN', dialCode: '+86', name: 'China', flag: flagFromIso('CN')},
  {iso: 'IN', dialCode: '+91', name: 'India', flag: flagFromIso('IN')},
  {iso: 'JP', dialCode: '+81', name: 'Japón', flag: flagFromIso('JP')},
  {iso: 'KR', dialCode: '+82', name: 'Corea del Sur', flag: flagFromIso('KR')},
  {iso: 'AU', dialCode: '+61', name: 'Australia', flag: flagFromIso('AU')},
  {iso: 'ZA', dialCode: '+27', name: 'Sudáfrica', flag: flagFromIso('ZA')},
  {iso: 'TR', dialCode: '+90', name: 'Turquía', flag: flagFromIso('TR')},
  {iso: 'EG', dialCode: '+20', name: 'Egipto', flag: flagFromIso('EG')},
  {iso: 'NG', dialCode: '+234', name: 'Nigeria', flag: flagFromIso('NG')},
  {iso: 'CU', dialCode: '+53', name: 'Cuba', flag: flagFromIso('CU')},
  {iso: 'AF', dialCode: '+93', name: 'Afganistán', flag: flagFromIso('AF')},
  {iso: 'AL', dialCode: '+355', name: 'Albania', flag: flagFromIso('AL')},
  {iso: 'DZ', dialCode: '+213', name: 'Argelia', flag: flagFromIso('DZ')},
  {iso: 'AD', dialCode: '+376', name: 'Andorra', flag: flagFromIso('AD')},
  {iso: 'AO', dialCode: '+244', name: 'Angola', flag: flagFromIso('AO')},
  {iso: 'AG', dialCode: '+1', name: 'Antigua y Barbuda', flag: flagFromIso('AG')},
  {iso: 'AM', dialCode: '+374', name: 'Armenia', flag: flagFromIso('AM')},
  {iso: 'AT', dialCode: '+43', name: 'Austria', flag: flagFromIso('AT')},
  {iso: 'AZ', dialCode: '+994', name: 'Azerbaiyán', flag: flagFromIso('AZ')},
  {iso: 'BH', dialCode: '+973', name: 'Baréin', flag: flagFromIso('BH')},
  {iso: 'BD', dialCode: '+880', name: 'Bangladesh', flag: flagFromIso('BD')},
  {iso: 'BB', dialCode: '+1', name: 'Barbados', flag: flagFromIso('BB')},
  {iso: 'BY', dialCode: '+375', name: 'Bielorrusia', flag: flagFromIso('BY')},
  {iso: 'BE', dialCode: '+32', name: 'Bélgica', flag: flagFromIso('BE')},
  {iso: 'BZ', dialCode: '+501', name: 'Belice', flag: flagFromIso('BZ')},
  {iso: 'BJ', dialCode: '+229', name: 'Benín', flag: flagFromIso('BJ')},
  {iso: 'BT', dialCode: '+975', name: 'Bután', flag: flagFromIso('BT')},
  {iso: 'BA', dialCode: '+387', name: 'Bosnia', flag: flagFromIso('BA')},
  {iso: 'BW', dialCode: '+267', name: 'Botsuana', flag: flagFromIso('BW')},
  {iso: 'BG', dialCode: '+359', name: 'Bulgaria', flag: flagFromIso('BG')},
  {iso: 'BF', dialCode: '+226', name: 'Burkina Faso', flag: flagFromIso('BF')},
  {iso: 'BI', dialCode: '+257', name: 'Burundi', flag: flagFromIso('BI')},
  {iso: 'KH', dialCode: '+855', name: 'Camboya', flag: flagFromIso('KH')},
  {iso: 'CM', dialCode: '+237', name: 'Camerún', flag: flagFromIso('CM')},
  {iso: 'CV', dialCode: '+238', name: 'Cabo Verde', flag: flagFromIso('CV')},
  {iso: 'CF', dialCode: '+236', name: 'Rep. Centroafricana', flag: flagFromIso('CF')},
  {iso: 'TD', dialCode: '+235', name: 'Chad', flag: flagFromIso('TD')},
  {iso: 'HK', dialCode: '+852', name: 'Hong Kong', flag: flagFromIso('HK')},
  {iso: 'GR', dialCode: '+30', name: 'Grecia', flag: flagFromIso('GR')},
  {iso: 'HU', dialCode: '+36', name: 'Hungría', flag: flagFromIso('HU')},
  {iso: 'IS', dialCode: '+354', name: 'Islandia', flag: flagFromIso('IS')},
  {iso: 'ID', dialCode: '+62', name: 'Indonesia', flag: flagFromIso('ID')},
  {iso: 'IR', dialCode: '+98', name: 'Irán', flag: flagFromIso('IR')},
  {iso: 'IQ', dialCode: '+964', name: 'Irak', flag: flagFromIso('IQ')},
  {iso: 'IE', dialCode: '+353', name: 'Irlanda', flag: flagFromIso('IE')},
  {iso: 'IL', dialCode: '+972', name: 'Israel', flag: flagFromIso('IL')},
  {iso: 'JM', dialCode: '+1', name: 'Jamaica', flag: flagFromIso('JM')},
  {iso: 'JO', dialCode: '+962', name: 'Jordania', flag: flagFromIso('JO')},
  {iso: 'KZ', dialCode: '+7', name: 'Kazajistán', flag: flagFromIso('KZ')},
  {iso: 'KE', dialCode: '+254', name: 'Kenia', flag: flagFromIso('KE')},
  {iso: 'KW', dialCode: '+965', name: 'Kuwait', flag: flagFromIso('KW')},
  {iso: 'KG', dialCode: '+996', name: 'Kirguistán', flag: flagFromIso('KG')},
  {iso: 'LV', dialCode: '+371', name: 'Letonia', flag: flagFromIso('LV')},
  {iso: 'LB', dialCode: '+961', name: 'Líbano', flag: flagFromIso('LB')},
  {iso: 'LY', dialCode: '+218', name: 'Libia', flag: flagFromIso('LY')},
  {iso: 'LT', dialCode: '+370', name: 'Lituania', flag: flagFromIso('LT')},
  {iso: 'LU', dialCode: '+352', name: 'Luxemburgo', flag: flagFromIso('LU')},
  {iso: 'MY', dialCode: '+60', name: 'Malasia', flag: flagFromIso('MY')},
  {iso: 'MT', dialCode: '+356', name: 'Malta', flag: flagFromIso('MT')},
  {iso: 'MA', dialCode: '+212', name: 'Marruecos', flag: flagFromIso('MA')},
  {iso: 'MU', dialCode: '+230', name: 'Mauricio', flag: flagFromIso('MU')},
  {iso: 'PL', dialCode: '+48', name: 'Polonia', flag: flagFromIso('PL')},
  {iso: 'RO', dialCode: '+40', name: 'Rumania', flag: flagFromIso('RO')},
  {iso: 'SA', dialCode: '+966', name: 'Arabia Saudita', flag: flagFromIso('SA')},
  {iso: 'ZA', dialCode: '+27', name: 'Sudáfrica', flag: flagFromIso('ZA')},
  {iso: 'SG', dialCode: '+65', name: 'Singapur', flag: flagFromIso('SG')},
  {iso: 'SK', dialCode: '+421', name: 'Eslovaquia', flag: flagFromIso('SK')},
  {iso: 'SI', dialCode: '+386', name: 'Eslovenia', flag: flagFromIso('SI')},
  {iso: 'SE', dialCode: '+46', name: 'Suecia', flag: flagFromIso('SE')},
  {iso: 'CH', dialCode: '+41', name: 'Suiza', flag: flagFromIso('CH')},
  {iso: 'SY', dialCode: '+963', name: 'Siria', flag: flagFromIso('SY')},
  {iso: 'TW', dialCode: '+886', name: 'Taiwán', flag: flagFromIso('TW')},
  {iso: 'TZ', dialCode: '+255', name: 'Tanzania', flag: flagFromIso('TZ')},
  {iso: 'TH', dialCode: '+66', name: 'Tailandia', flag: flagFromIso('TH')},
  {iso: 'TN', dialCode: '+216', name: 'Túnez', flag: flagFromIso('TN')},
  {iso: 'UA', dialCode: '+380', name: 'Ucrania', flag: flagFromIso('UA')},
  {iso: 'AE', dialCode: '+971', name: 'EAU', flag: flagFromIso('AE')},
];
